### ISSUE TITLE
Implement function to work with camera

### ISSUE THREAD

**Issue by Talkasi** [Talkasi/call-app#1]
In this issue information about libraries to use camera should be found first. Chosen library should work on Fedora 36, RedHat Enterprise Linux 9 in the same way.

Then should be implemetned function which:

- Gets input from a camera
- Gives back this input

Code should be written on Python.

**Comment by Talkasi** [comment]
@anton2920, take a look please

**Comment by anton2920** [comment]
@Talkasi, I don't see a pull request I should do a review for. Can you please create one?

**Comment by Talkasi** [comment]
@anton2920, created pull request, take a look, please. I will resolve all the conflicts if everything else is fine.

**Comment by Talkasi** [comment]
Have a new idea, so assigning miself.

**Comment by anton2920** [comment]
@Talkasi, please see discussions.

**Comment by Talkasi** [comment]
@anton2920, please take a look again.

**Comment by anton2920** [comment]
Looks OK. Left a few minor discussions.

**Comment by Talkasi** [comment]
Answered everything. Please take a look.

**Comment by anton2920** [comment]
Replied to your question.

**Comment by Talkasi** [comment]
Commited last changes. Is it complitelly done now?

**Comment by anton2920** [comment]
Yes. Approved changes.
