### ISSUE TITLE
Implement function to work with microphone

### ISSUE THREAD

**Issue by Talkasi** [Talkasi/call-app#2]
In this issue information about libraries to use microphone should be found first. Chosen library should work on Fedora 36, RedHat Enterprise Linux 9 in the same way.

Then should be implemetned function which:
- Gets input from a microphone
- Plays back this input

Code should be written on Python.

**Comment by anton2920** [comment]
Basically, we have these three options:

- [python-sounddevice](https://python-sounddevice.readthedocs.io/en/latest/);
- [pyaudio](https://people.csail.mit.edu/hubert/pyaudio/);
- write bindings to anything we want ourselves (like [this](https://gist.github.com/ignacysokolowski/3973029)).

First two are the bindings to the [PortAudio](http://www.portaudio.com/) and I've seen more internet people using the first one, so we can use it as well.

What do you think?

**Comment by Talkasi** [comment]
[Python-sounddevice](https://python-sounddevice.readthedocs.io/en/latest/) seems the most suitable variant, so let's use it as our library.

**Comment by anton2920** [comment]
Implemented a simple `loopback()` function.

@Talkasi, please take a look at #3.

**Comment by Talkasi** [comment]
Everything is great, except the one thing will be discussed on a call.
